version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql
  server:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db: